

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _303TeamTest.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TestDatabaseEntities : DbContext
{
    public TestDatabaseEntities()
        : base("name=TestDatabaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CustomerDetailsData> CustomerDetailsData { get; set; }

    public virtual DbSet<CustomerRoles> CustomerRoles { get; set; }

    public virtual DbSet<Customers> Customers { get; set; }

    public virtual DbSet<Role> Role { get; set; }

}

}

