
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _303TeamTest.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Customers
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customers()
    {

        this.CustomerRoles = new HashSet<CustomerRoles>();

    }


    public long CustomerId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public bool IsDisabled { get; set; }

    public Nullable<long> DetailsId { get; set; }



    public virtual CustomerDetailsData CustomerDetailsData { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CustomerRoles> CustomerRoles { get; set; }

}

}
