
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _303TeamTest.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CustomerRoles
{

    public long Id { get; set; }

    public long CustomerId { get; set; }

    public long RoleId { get; set; }



    public virtual Customers Customers { get; set; }

    public virtual Role Role { get; set; }

}

}
